### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
do_eval: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset_dir: ../DATA/Training_Data
dataset: maze_train_stepwise_sft_both
eval_dataset: maze_test_unseen_stepwise_sft_trajectory
template: qwen2_vl
cutoff_len: 2048
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: ../DATA/Training_Result/qwen2.5-vl-3b/lora/maze_sft_both
logging_steps: 100
save_strategy: steps
save_steps: 3000
eval_strategy: steps
eval_steps: 3000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 20.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
per_device_eval_batch_size: 1
